# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_StrumpackSparseSolver')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_StrumpackSparseSolver')
    _StrumpackSparseSolver = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_StrumpackSparseSolver', [dirname(__file__)])
        except ImportError:
            import _StrumpackSparseSolver
            return _StrumpackSparseSolver
        try:
            _mod = imp.load_module('_StrumpackSparseSolver', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _StrumpackSparseSolver = swig_import_helper()
    del swig_import_helper
else:
    import _StrumpackSparseSolver
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class StrumpackSolverBase(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StrumpackSolverBase, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StrumpackSolverBase, name)
    __repr__ = _swig_repr

    def factor(self):
        return _StrumpackSparseSolver.StrumpackSolverBase_factor(self)

    def reorder(self):
        return _StrumpackSparseSolver.StrumpackSolverBase_reorder(self)

    def reorder_regular(self, nx, ny, nz):
        return _StrumpackSparseSolver.StrumpackSolverBase_reorder_regular(self, nx, ny, nz)

    def set_verbose(self, v):
        return _StrumpackSparseSolver.StrumpackSolverBase_set_verbose(self, v)

    def set_maxit(self, maxit):
        return _StrumpackSparseSolver.StrumpackSolverBase_set_maxit(self, maxit)

    def set_gmres_restart(self, m):
        return _StrumpackSparseSolver.StrumpackSolverBase_set_gmres_restart(self, m)

    def set_rel_tol(self, tol):
        return _StrumpackSparseSolver.StrumpackSolverBase_set_rel_tol(self, tol)

    def set_abs_tol(self, tol):
        return _StrumpackSparseSolver.StrumpackSolverBase_set_abs_tol(self, tol)

    def set_nd_param(self, nd_param):
        return _StrumpackSparseSolver.StrumpackSolverBase_set_nd_param(self, nd_param)

    def set_reordering_method(self, m):
        return _StrumpackSparseSolver.StrumpackSolverBase_set_reordering_method(self, m)

    def set_GramSchmidt_type(self, t):
        return _StrumpackSparseSolver.StrumpackSolverBase_set_GramSchmidt_type(self, t)

    def set_mc64job(self, job):
        return _StrumpackSparseSolver.StrumpackSolverBase_set_mc64job(self, job)

    def set_matching(self, job):
        return _StrumpackSparseSolver.StrumpackSolverBase_set_matching(self, job)

    def set_Krylov_solver(self, solver_type):
        return _StrumpackSparseSolver.StrumpackSolverBase_set_Krylov_solver(self, solver_type)

    def enable_HSS(self):
        return _StrumpackSparseSolver.StrumpackSolverBase_enable_HSS(self)

    def disable_HSS(self):
        return _StrumpackSparseSolver.StrumpackSolverBase_disable_HSS(self)

    def set_HSS_min_front_size(self, size):
        return _StrumpackSparseSolver.StrumpackSolverBase_set_HSS_min_front_size(self, size)

    def set_HSS_min_sep_size(self, size):
        return _StrumpackSparseSolver.StrumpackSolverBase_set_HSS_min_sep_size(self, size)

    def set_HSS_max_rank(self, max_rank):
        return _StrumpackSparseSolver.StrumpackSolverBase_set_HSS_max_rank(self, max_rank)

    def set_HSS_leaf_size(self, leaf_size):
        return _StrumpackSparseSolver.StrumpackSolverBase_set_HSS_leaf_size(self, leaf_size)

    def set_HSS_rel_tol(self, rctol):
        return _StrumpackSparseSolver.StrumpackSolverBase_set_HSS_rel_tol(self, rctol)

    def set_HSS_abs_tol(self, actol):
        return _StrumpackSparseSolver.StrumpackSolverBase_set_HSS_abs_tol(self, actol)

    def get_verbose(self):
        return _StrumpackSparseSolver.StrumpackSolverBase_get_verbose(self)

    def get_maxit(self):
        return _StrumpackSparseSolver.StrumpackSolverBase_get_maxit(self)

    def get_rel_tol(self):
        return _StrumpackSparseSolver.StrumpackSolverBase_get_rel_tol(self)

    def get_abs_tol(self):
        return _StrumpackSparseSolver.StrumpackSolverBase_get_abs_tol(self)

    def get_nd_param(self):
        return _StrumpackSparseSolver.StrumpackSolverBase_get_nd_param(self)

    def get_reordering_method(self):
        return _StrumpackSparseSolver.StrumpackSolverBase_get_reordering_method(self)

    def get_mc64job(self):
        return _StrumpackSparseSolver.StrumpackSolverBase_get_mc64job(self)

    def get_matching(self):
        return _StrumpackSparseSolver.StrumpackSolverBase_get_matching(self)

    def get_Krylov_solver(self):
        return _StrumpackSparseSolver.StrumpackSolverBase_get_Krylov_solver(self)

    def get_HSS_min_front_size(self):
        return _StrumpackSparseSolver.StrumpackSolverBase_get_HSS_min_front_size(self)

    def get_HSS_min_sep_size(self):
        return _StrumpackSparseSolver.StrumpackSolverBase_get_HSS_min_sep_size(self)

    def get_HSS_max_rank(self):
        return _StrumpackSparseSolver.StrumpackSolverBase_get_HSS_max_rank(self)

    def get_HSS_leaf_size(self):
        return _StrumpackSparseSolver.StrumpackSolverBase_get_HSS_leaf_size(self)

    def get_HSS_rel_tol(self):
        return _StrumpackSparseSolver.StrumpackSolverBase_get_HSS_rel_tol(self)

    def get_HSS_abs_tol(self):
        return _StrumpackSparseSolver.StrumpackSolverBase_get_HSS_abs_tol(self)

    def get_its(self):
        return _StrumpackSparseSolver.StrumpackSolverBase_get_its(self)

    def get_rank(self):
        return _StrumpackSparseSolver.StrumpackSolverBase_get_rank(self)

    def get_factor_nonzeros(self):
        return _StrumpackSparseSolver.StrumpackSolverBase_get_factor_nonzeros(self)

    def get_factor_memory(self):
        return _StrumpackSparseSolver.StrumpackSolverBase_get_factor_memory(self)

    def __init__(self):
        this = _StrumpackSparseSolver.new_StrumpackSolverBase()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _StrumpackSparseSolver.delete_StrumpackSolverBase
    __del__ = lambda self: None
StrumpackSolverBase_swigregister = _StrumpackSparseSolver.StrumpackSolverBase_swigregister
StrumpackSolverBase_swigregister(StrumpackSolverBase)

class SStrumpackSolver(StrumpackSolverBase):
    __swig_setmethods__ = {}
    for _s in [StrumpackSolverBase]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SStrumpackSolver, name, value)
    __swig_getmethods__ = {}
    for _s in [StrumpackSolverBase]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, SStrumpackSolver, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _StrumpackSparseSolver.new_SStrumpackSolver()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _StrumpackSparseSolver.delete_SStrumpackSolver
    __del__ = lambda self: None

    def set_csr_matrix(self, N, row_ptr, col_ind, values, symmetric_pattern):
        return _StrumpackSparseSolver.SStrumpackSolver_set_csr_matrix(self, N, row_ptr, col_ind, values, symmetric_pattern)

    def solve(self, b, x, use_initial_guess):
        return _StrumpackSparseSolver.SStrumpackSolver_solve(self, b, x, use_initial_guess)
SStrumpackSolver_swigregister = _StrumpackSparseSolver.SStrumpackSolver_swigregister
SStrumpackSolver_swigregister(SStrumpackSolver)

STRUMPACK_FLOAT = _StrumpackSparseSolver.STRUMPACK_FLOAT
STRUMPACK_DOUBLE = _StrumpackSparseSolver.STRUMPACK_DOUBLE
STRUMPACK_FLOATCOMPLEX = _StrumpackSparseSolver.STRUMPACK_FLOATCOMPLEX
STRUMPACK_DOUBLECOMPLEX = _StrumpackSparseSolver.STRUMPACK_DOUBLECOMPLEX
STRUMPACK_FLOAT_64 = _StrumpackSparseSolver.STRUMPACK_FLOAT_64
STRUMPACK_DOUBLE_64 = _StrumpackSparseSolver.STRUMPACK_DOUBLE_64
STRUMPACK_FLOATCOMPLEX_64 = _StrumpackSparseSolver.STRUMPACK_FLOATCOMPLEX_64
STRUMPACK_DOUBLECOMPLEX_64 = _StrumpackSparseSolver.STRUMPACK_DOUBLECOMPLEX_64
STRUMPACK_MT = _StrumpackSparseSolver.STRUMPACK_MT
STRUMPACK_MPI_DIST = _StrumpackSparseSolver.STRUMPACK_MPI_DIST
class STRUMPACK_SparseSolver(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, STRUMPACK_SparseSolver, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, STRUMPACK_SparseSolver, name)
    __repr__ = _swig_repr
    __swig_setmethods__["solver"] = _StrumpackSparseSolver.STRUMPACK_SparseSolver_solver_set
    __swig_getmethods__["solver"] = _StrumpackSparseSolver.STRUMPACK_SparseSolver_solver_get
    if _newclass:
        solver = _swig_property(_StrumpackSparseSolver.STRUMPACK_SparseSolver_solver_get, _StrumpackSparseSolver.STRUMPACK_SparseSolver_solver_set)
    __swig_setmethods__["precision"] = _StrumpackSparseSolver.STRUMPACK_SparseSolver_precision_set
    __swig_getmethods__["precision"] = _StrumpackSparseSolver.STRUMPACK_SparseSolver_precision_get
    if _newclass:
        precision = _swig_property(_StrumpackSparseSolver.STRUMPACK_SparseSolver_precision_get, _StrumpackSparseSolver.STRUMPACK_SparseSolver_precision_set)
    __swig_setmethods__["interface"] = _StrumpackSparseSolver.STRUMPACK_SparseSolver_interface_set
    __swig_getmethods__["interface"] = _StrumpackSparseSolver.STRUMPACK_SparseSolver_interface_get
    if _newclass:
        interface = _swig_property(_StrumpackSparseSolver.STRUMPACK_SparseSolver_interface_get, _StrumpackSparseSolver.STRUMPACK_SparseSolver_interface_set)

    def __init__(self):
        this = _StrumpackSparseSolver.new_STRUMPACK_SparseSolver()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _StrumpackSparseSolver.delete_STRUMPACK_SparseSolver
    __del__ = lambda self: None
STRUMPACK_SparseSolver_swigregister = _StrumpackSparseSolver.STRUMPACK_SparseSolver_swigregister
STRUMPACK_SparseSolver_swigregister(STRUMPACK_SparseSolver)

class floatcomplex(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, floatcomplex, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, floatcomplex, name)
    __repr__ = _swig_repr
    __swig_setmethods__["r"] = _StrumpackSparseSolver.floatcomplex_r_set
    __swig_getmethods__["r"] = _StrumpackSparseSolver.floatcomplex_r_get
    if _newclass:
        r = _swig_property(_StrumpackSparseSolver.floatcomplex_r_get, _StrumpackSparseSolver.floatcomplex_r_set)
    __swig_setmethods__["i"] = _StrumpackSparseSolver.floatcomplex_i_set
    __swig_getmethods__["i"] = _StrumpackSparseSolver.floatcomplex_i_get
    if _newclass:
        i = _swig_property(_StrumpackSparseSolver.floatcomplex_i_get, _StrumpackSparseSolver.floatcomplex_i_set)

    def __init__(self):
        this = _StrumpackSparseSolver.new_floatcomplex()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _StrumpackSparseSolver.delete_floatcomplex
    __del__ = lambda self: None
floatcomplex_swigregister = _StrumpackSparseSolver.floatcomplex_swigregister
floatcomplex_swigregister(floatcomplex)

class doublecomplex(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, doublecomplex, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, doublecomplex, name)
    __repr__ = _swig_repr
    __swig_setmethods__["r"] = _StrumpackSparseSolver.doublecomplex_r_set
    __swig_getmethods__["r"] = _StrumpackSparseSolver.doublecomplex_r_get
    if _newclass:
        r = _swig_property(_StrumpackSparseSolver.doublecomplex_r_get, _StrumpackSparseSolver.doublecomplex_r_set)
    __swig_setmethods__["i"] = _StrumpackSparseSolver.doublecomplex_i_set
    __swig_getmethods__["i"] = _StrumpackSparseSolver.doublecomplex_i_get
    if _newclass:
        i = _swig_property(_StrumpackSparseSolver.doublecomplex_i_get, _StrumpackSparseSolver.doublecomplex_i_set)

    def __init__(self):
        this = _StrumpackSparseSolver.new_doublecomplex()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _StrumpackSparseSolver.delete_doublecomplex
    __del__ = lambda self: None
doublecomplex_swigregister = _StrumpackSparseSolver.doublecomplex_swigregister
doublecomplex_swigregister(doublecomplex)

STRUMPACK_NATURAL = _StrumpackSparseSolver.STRUMPACK_NATURAL
STRUMPACK_METIS = _StrumpackSparseSolver.STRUMPACK_METIS
STRUMPACK_PARMETIS = _StrumpackSparseSolver.STRUMPACK_PARMETIS
STRUMPACK_SCOTCH = _StrumpackSparseSolver.STRUMPACK_SCOTCH
STRUMPACK_PTSCOTCH = _StrumpackSparseSolver.STRUMPACK_PTSCOTCH
STRUMPACK_RCM = _StrumpackSparseSolver.STRUMPACK_RCM
STRUMPACK_GEOMETRIC = _StrumpackSparseSolver.STRUMPACK_GEOMETRIC
STRUMPACK_CLASSICAL = _StrumpackSparseSolver.STRUMPACK_CLASSICAL
STRUMPACK_MODIFIED = _StrumpackSparseSolver.STRUMPACK_MODIFIED
STRUMPACK_NORMAL = _StrumpackSparseSolver.STRUMPACK_NORMAL
STRUMPACK_UNIFORM = _StrumpackSparseSolver.STRUMPACK_UNIFORM
STRUMPACK_LINEAR = _StrumpackSparseSolver.STRUMPACK_LINEAR
STRUMPACK_MERSENNE = _StrumpackSparseSolver.STRUMPACK_MERSENNE
STRUMPACK_AUTO = _StrumpackSparseSolver.STRUMPACK_AUTO
STRUMPACK_DIRECT = _StrumpackSparseSolver.STRUMPACK_DIRECT
STRUMPACK_REFINE = _StrumpackSparseSolver.STRUMPACK_REFINE
STRUMPACK_PREC_GMRES = _StrumpackSparseSolver.STRUMPACK_PREC_GMRES
STRUMPACK_GMRES = _StrumpackSparseSolver.STRUMPACK_GMRES
STRUMPACK_PREC_BICGSTAB = _StrumpackSparseSolver.STRUMPACK_PREC_BICGSTAB
STRUMPACK_BICGSTAB = _StrumpackSparseSolver.STRUMPACK_BICGSTAB
STRUMPACK_SUCCESS = _StrumpackSparseSolver.STRUMPACK_SUCCESS
STRUMPACK_MATRIX_NOT_SET = _StrumpackSparseSolver.STRUMPACK_MATRIX_NOT_SET
STRUMPACK_REORDERING_ERROR = _StrumpackSparseSolver.STRUMPACK_REORDERING_ERROR

def STRUMPACK_init_mt(S, precision, interface, argc, argv, verbose):
    return _StrumpackSparseSolver.STRUMPACK_init_mt(S, precision, interface, argc, argv, verbose)
STRUMPACK_init_mt = _StrumpackSparseSolver.STRUMPACK_init_mt

def STRUMPACK_destroy(S):
    return _StrumpackSparseSolver.STRUMPACK_destroy(S)
STRUMPACK_destroy = _StrumpackSparseSolver.STRUMPACK_destroy

def STRUMPACK_set_csr_matrix(S, N, row_ptr, col_ind, values, symmetric_pattern):
    return _StrumpackSparseSolver.STRUMPACK_set_csr_matrix(S, N, row_ptr, col_ind, values, symmetric_pattern)
STRUMPACK_set_csr_matrix = _StrumpackSparseSolver.STRUMPACK_set_csr_matrix

def STRUMPACK_solve(S, b, x, use_initial_guess):
    return _StrumpackSparseSolver.STRUMPACK_solve(S, b, x, use_initial_guess)
STRUMPACK_solve = _StrumpackSparseSolver.STRUMPACK_solve

def STRUMPACK_set_from_options(S):
    return _StrumpackSparseSolver.STRUMPACK_set_from_options(S)
STRUMPACK_set_from_options = _StrumpackSparseSolver.STRUMPACK_set_from_options

def STRUMPACK_reorder(S):
    return _StrumpackSparseSolver.STRUMPACK_reorder(S)
STRUMPACK_reorder = _StrumpackSparseSolver.STRUMPACK_reorder

def STRUMPACK_reorder_regular(S, nx, ny, nz):
    return _StrumpackSparseSolver.STRUMPACK_reorder_regular(S, nx, ny, nz)
STRUMPACK_reorder_regular = _StrumpackSparseSolver.STRUMPACK_reorder_regular

def STRUMPACK_factor(S):
    return _StrumpackSparseSolver.STRUMPACK_factor(S)
STRUMPACK_factor = _StrumpackSparseSolver.STRUMPACK_factor

def STRUMPACK_set_verbose(S, v):
    return _StrumpackSparseSolver.STRUMPACK_set_verbose(S, v)
STRUMPACK_set_verbose = _StrumpackSparseSolver.STRUMPACK_set_verbose

def STRUMPACK_set_maxit(S, maxit):
    return _StrumpackSparseSolver.STRUMPACK_set_maxit(S, maxit)
STRUMPACK_set_maxit = _StrumpackSparseSolver.STRUMPACK_set_maxit

def STRUMPACK_set_gmres_restart(S, m):
    return _StrumpackSparseSolver.STRUMPACK_set_gmres_restart(S, m)
STRUMPACK_set_gmres_restart = _StrumpackSparseSolver.STRUMPACK_set_gmres_restart

def STRUMPACK_set_rel_tol(S, tol):
    return _StrumpackSparseSolver.STRUMPACK_set_rel_tol(S, tol)
STRUMPACK_set_rel_tol = _StrumpackSparseSolver.STRUMPACK_set_rel_tol

def STRUMPACK_set_abs_tol(S, tol):
    return _StrumpackSparseSolver.STRUMPACK_set_abs_tol(S, tol)
STRUMPACK_set_abs_tol = _StrumpackSparseSolver.STRUMPACK_set_abs_tol

def STRUMPACK_set_nd_param(S, nd_param):
    return _StrumpackSparseSolver.STRUMPACK_set_nd_param(S, nd_param)
STRUMPACK_set_nd_param = _StrumpackSparseSolver.STRUMPACK_set_nd_param

def STRUMPACK_set_reordering_method(S, m):
    return _StrumpackSparseSolver.STRUMPACK_set_reordering_method(S, m)
STRUMPACK_set_reordering_method = _StrumpackSparseSolver.STRUMPACK_set_reordering_method

def STRUMPACK_set_GramSchmidt_type(S, t):
    return _StrumpackSparseSolver.STRUMPACK_set_GramSchmidt_type(S, t)
STRUMPACK_set_GramSchmidt_type = _StrumpackSparseSolver.STRUMPACK_set_GramSchmidt_type

def STRUMPACK_set_mc64job(S, job):
    return _StrumpackSparseSolver.STRUMPACK_set_mc64job(S, job)
STRUMPACK_set_mc64job = _StrumpackSparseSolver.STRUMPACK_set_mc64job

def STRUMPACK_set_matching(S, job):
    return _StrumpackSparseSolver.STRUMPACK_set_matching(S, job)
STRUMPACK_set_matching = _StrumpackSparseSolver.STRUMPACK_set_matching

def STRUMPACK_set_Krylov_solver(S, solver_type):
    return _StrumpackSparseSolver.STRUMPACK_set_Krylov_solver(S, solver_type)
STRUMPACK_set_Krylov_solver = _StrumpackSparseSolver.STRUMPACK_set_Krylov_solver

def STRUMPACK_enable_HSS(S):
    return _StrumpackSparseSolver.STRUMPACK_enable_HSS(S)
STRUMPACK_enable_HSS = _StrumpackSparseSolver.STRUMPACK_enable_HSS

def STRUMPACK_disable_HSS(S):
    return _StrumpackSparseSolver.STRUMPACK_disable_HSS(S)
STRUMPACK_disable_HSS = _StrumpackSparseSolver.STRUMPACK_disable_HSS

def STRUMPACK_set_HSS_min_front_size(S, size):
    return _StrumpackSparseSolver.STRUMPACK_set_HSS_min_front_size(S, size)
STRUMPACK_set_HSS_min_front_size = _StrumpackSparseSolver.STRUMPACK_set_HSS_min_front_size

def STRUMPACK_set_HSS_min_sep_size(S, size):
    return _StrumpackSparseSolver.STRUMPACK_set_HSS_min_sep_size(S, size)
STRUMPACK_set_HSS_min_sep_size = _StrumpackSparseSolver.STRUMPACK_set_HSS_min_sep_size

def STRUMPACK_set_HSS_max_rank(S, max_rank):
    return _StrumpackSparseSolver.STRUMPACK_set_HSS_max_rank(S, max_rank)
STRUMPACK_set_HSS_max_rank = _StrumpackSparseSolver.STRUMPACK_set_HSS_max_rank

def STRUMPACK_set_HSS_leaf_size(S, leaf_size):
    return _StrumpackSparseSolver.STRUMPACK_set_HSS_leaf_size(S, leaf_size)
STRUMPACK_set_HSS_leaf_size = _StrumpackSparseSolver.STRUMPACK_set_HSS_leaf_size

def STRUMPACK_set_HSS_rel_tol(S, rctol):
    return _StrumpackSparseSolver.STRUMPACK_set_HSS_rel_tol(S, rctol)
STRUMPACK_set_HSS_rel_tol = _StrumpackSparseSolver.STRUMPACK_set_HSS_rel_tol

def STRUMPACK_set_HSS_abs_tol(S, actol):
    return _StrumpackSparseSolver.STRUMPACK_set_HSS_abs_tol(S, actol)
STRUMPACK_set_HSS_abs_tol = _StrumpackSparseSolver.STRUMPACK_set_HSS_abs_tol

def STRUMPACK_verbose(S):
    return _StrumpackSparseSolver.STRUMPACK_verbose(S)
STRUMPACK_verbose = _StrumpackSparseSolver.STRUMPACK_verbose

def STRUMPACK_maxit(S):
    return _StrumpackSparseSolver.STRUMPACK_maxit(S)
STRUMPACK_maxit = _StrumpackSparseSolver.STRUMPACK_maxit

def STRUMPACK_rel_tol(S):
    return _StrumpackSparseSolver.STRUMPACK_rel_tol(S)
STRUMPACK_rel_tol = _StrumpackSparseSolver.STRUMPACK_rel_tol

def STRUMPACK_abs_tol(S):
    return _StrumpackSparseSolver.STRUMPACK_abs_tol(S)
STRUMPACK_abs_tol = _StrumpackSparseSolver.STRUMPACK_abs_tol

def STRUMPACK_nd_param(S):
    return _StrumpackSparseSolver.STRUMPACK_nd_param(S)
STRUMPACK_nd_param = _StrumpackSparseSolver.STRUMPACK_nd_param

def STRUMPACK_reordering_method(S):
    return _StrumpackSparseSolver.STRUMPACK_reordering_method(S)
STRUMPACK_reordering_method = _StrumpackSparseSolver.STRUMPACK_reordering_method

def STRUMPACK_GramSchmidt_type(S):
    return _StrumpackSparseSolver.STRUMPACK_GramSchmidt_type(S)
STRUMPACK_GramSchmidt_type = _StrumpackSparseSolver.STRUMPACK_GramSchmidt_type

def STRUMPACK_mc64job(S):
    return _StrumpackSparseSolver.STRUMPACK_mc64job(S)
STRUMPACK_mc64job = _StrumpackSparseSolver.STRUMPACK_mc64job

def STRUMPACK_matching(S):
    return _StrumpackSparseSolver.STRUMPACK_matching(S)
STRUMPACK_matching = _StrumpackSparseSolver.STRUMPACK_matching

def STRUMPACK_Krylov_solver(S):
    return _StrumpackSparseSolver.STRUMPACK_Krylov_solver(S)
STRUMPACK_Krylov_solver = _StrumpackSparseSolver.STRUMPACK_Krylov_solver

def STRUMPACK_HSS_min_front_size(S):
    return _StrumpackSparseSolver.STRUMPACK_HSS_min_front_size(S)
STRUMPACK_HSS_min_front_size = _StrumpackSparseSolver.STRUMPACK_HSS_min_front_size

def STRUMPACK_HSS_min_sep_size(S):
    return _StrumpackSparseSolver.STRUMPACK_HSS_min_sep_size(S)
STRUMPACK_HSS_min_sep_size = _StrumpackSparseSolver.STRUMPACK_HSS_min_sep_size

def STRUMPACK_HSS_max_rank(S):
    return _StrumpackSparseSolver.STRUMPACK_HSS_max_rank(S)
STRUMPACK_HSS_max_rank = _StrumpackSparseSolver.STRUMPACK_HSS_max_rank

def STRUMPACK_HSS_leaf_size(S):
    return _StrumpackSparseSolver.STRUMPACK_HSS_leaf_size(S)
STRUMPACK_HSS_leaf_size = _StrumpackSparseSolver.STRUMPACK_HSS_leaf_size

def STRUMPACK_HSS_rel_tol(S):
    return _StrumpackSparseSolver.STRUMPACK_HSS_rel_tol(S)
STRUMPACK_HSS_rel_tol = _StrumpackSparseSolver.STRUMPACK_HSS_rel_tol

def STRUMPACK_HSS_abs_tol(S):
    return _StrumpackSparseSolver.STRUMPACK_HSS_abs_tol(S)
STRUMPACK_HSS_abs_tol = _StrumpackSparseSolver.STRUMPACK_HSS_abs_tol

def STRUMPACK_its(S):
    return _StrumpackSparseSolver.STRUMPACK_its(S)
STRUMPACK_its = _StrumpackSparseSolver.STRUMPACK_its

def STRUMPACK_rank(S):
    return _StrumpackSparseSolver.STRUMPACK_rank(S)
STRUMPACK_rank = _StrumpackSparseSolver.STRUMPACK_rank

def STRUMPACK_factor_nonzeros(S):
    return _StrumpackSparseSolver.STRUMPACK_factor_nonzeros(S)
STRUMPACK_factor_nonzeros = _StrumpackSparseSolver.STRUMPACK_factor_nonzeros

def STRUMPACK_factor_memory(S):
    return _StrumpackSparseSolver.STRUMPACK_factor_memory(S)
STRUMPACK_factor_memory = _StrumpackSparseSolver.STRUMPACK_factor_memory
# This file is compatible with both classic and new-style classes.


